#!/bin/bash

if [[ -z $1 || -z $2 ]]
then 
	echo Please run with via the following: $0 postgres_host postgres_user
	exit
fi

echo "Starting Alliancemine DB Build: Host: $1 User: $2"
date

echo "Obtaining YeastMine Data from S3 Bucket"
aws s3 cp s3://agr-db-backups/alliancemine/intermine/ /data/intermine --recursive

fasta_sources=(alliance-wb-fasta alliance-fb-fasta alliance-zfin-fasta alliance-mgi-fasta alliance-rgd-fasta)
ontology_sources=(do go eco mmo emapa zfa wbbt fbbt so psi-mi-ontology go-slim)
sgd_sources=(sgd sgd-gff sgd-gff-utr sgd-db-utr fungi-homologs cgob-homologs cglabrata-homologs pombe-homologs homolog-genes sgd-complementation-db sgd-complexes sgd-protein-properties sgd-protein-ntermini)
alliance_sources=(alliance-genes go-annotation alliance-disease alliance-orthologs alliance-alleles alliance-expression entrez-organism)
postprocess_sources=(create-references do-sources transfer-sequences create-attribute-indexes summarise-objectstore)
solr_indexes=(create-autocomplete-index create-search-index)

echo createdb -U $2 -h $1 alliancemine || true
createdb -U $2 -h $1 alliancemine || true
echo createdb -U $2 -h $1 items-alliancemine || true
createdb -U $2 -h $1 items-alliancemine || true
echo ./gradlew --no-daemon builddb
./gradlew --no-daemon builddb
date

for i in "${fasta_sources[@]}"
do
	echo "./gradlew --no-daemon integrate -Psource=$i"
	./gradlew --no-daemon --stacktrace integrate -Psource=$i
	date
done

for i in "${ontology_sources[@]}"
do
	echo "./gradlew --no-daemon integrate -Psource=$i"
	./gradlew --no-daemon --stacktrace integrate -Psource=$i
	date
done

for i in "${sgd_sources[@]}"
do
	echo "./gradlew --no-daemon integrate -Psource=$i"
	./gradlew --no-daemon --stacktrace integrate -Psource=$i
	date
done

for i in "${alliance_sources[@]}"
do
	echo "./gradlew --no-daemon integrate -Psource=$i"
	./gradlew --no-daemon --stacktrace integrate -Psource=$i
	date
done

for i in "${postprocess_sources[@]}"
do
	echo "./gradlew --no-daemon postprocess -Pprocess=$i"
	./gradlew --no-daemon --stacktrace postprocess -Pprocess=$i
	date
done

echo pg_dump -F c -U $2 -h $1 -f /root/data/alliancemine.dump alliancemine
pg_dump -F c -U $2 -h $1 -f /root/data/alliancemine.dump alliancemine

date

echo "Backup DB File to S3: aws s3 cp /root/data/alliancemine.dump s3://agr-db-backups/alliancemine/stage/`date "+%Y-%m-%d_%H:%M:%S".dump`"
aws s3 cp /root/data/alliancemine.dump s3://agr-db-backups/alliancemine/stage/`date "+%Y-%m-%d_%H:%M:%S".dump`

echo "Finished Alliancemine DB Build"
date

# # Copy properties
# echo "Updating Solr URLs in property files..."
# echo "index.solrurl=http://agr.local.alliancemine.solr.server:8983/solr/alliancemine-search" >> dbmodel/resources/keyword_search.properties
# echo "autocomplete.solrurl=http://agr.local.alliancemine.solr.server:8983/solr/alliancemine-autocomplete" >> dbmodel/resources/objectstoresummary.config.properties
# echo "Solr URLs updated."

# # Run load Solr
# echo "Loading Solr with new data..."
# ./build_solr postgres postgres
# echo "Solr data load complete."

# aws secretsmanager get-secret-value --region=us-east-1 --secret-id IntermineStagePropertiesFile --query SecretString --output text > alliancemine.properties

# # Deploy Tomcat
# echo "Redeploying Tomcat server..."
# ./gradlew cargoRedeployRemote --stacktrace
# echo "Tomcat redeployed successfully."